// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX2PcSF7UjKEcZNiVn7C3v0qAKC2FyTTA',
    appId: '1:959024398937:web:6ceeff6049ca4cb97ca748',
    messagingSenderId: '959024398937',
    projectId: 'fir-operations-3b2a2',
    authDomain: 'fir-operations-3b2a2.firebaseapp.com',
    storageBucket: 'fir-operations-3b2a2.appspot.com',
    measurementId: 'G-BE326FXZMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5gX-ACiVwEFoBspVTsaoXzP6U36UlwOk',
    appId: '1:959024398937:android:67195748639ee5387ca748',
    messagingSenderId: '959024398937',
    projectId: 'fir-operations-3b2a2',
    storageBucket: 'fir-operations-3b2a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaYY8p4LLMcvpX4yjAges8ioiEoRSmTXM',
    appId: '1:959024398937:ios:f22362569a1206a17ca748',
    messagingSenderId: '959024398937',
    projectId: 'fir-operations-3b2a2',
    storageBucket: 'fir-operations-3b2a2.appspot.com',
    iosBundleId: 'com.example.firebaseOperations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaYY8p4LLMcvpX4yjAges8ioiEoRSmTXM',
    appId: '1:959024398937:ios:af89dc03540538737ca748',
    messagingSenderId: '959024398937',
    projectId: 'fir-operations-3b2a2',
    storageBucket: 'fir-operations-3b2a2.appspot.com',
    iosBundleId: 'com.example.firebaseOperations.RunnerTests',
  );
}
